name: Elixir Mix Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: '1.13.4'
            otp: '25.3'
          - elixir: '1.14.5'
            otp: '26.2'
          - elixir: '1.15.8'
            otp: '26.2'
          - elixir: '1.16.3'
            otp: '26.2'
          - elixir: '1.17.2'
            otp: '27.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Run tests
        run: mix test
